### ISSUE TITLE
DZ rewiev lessons 3

### ISSUE THREAD

**Issue by andrewmarushko** [YurchukYaroslav/YurchukYaroslav.github.io#1]
# НЕ ЗАЧЕТ

нужно пофиксить ряд ховер эффектов

<img width="272" alt="screenshot 2015-11-02 22 08 36" src="https://cloud.githubusercontent.com/assets/4026421/10892910/a884a084-81ae-11e5-8cd4-2312951cbc26.png">
<img width="281" alt="screenshot 2015-11-02 22 08 45" src="https://cloud.githubusercontent.com/assets/4026421/10892911/a8876170-81ae-11e5-9e06-59ce82981985.png">

так вынести блок копирайта из вне списка

<img width="400" alt="screenshot 2015-11-02 22 09 05" src="https://cloud.githubusercontent.com/assets/4026421/10892925/be358038-81ae-11e5-8f35-0855a0da5878.png">

**Comment by YurchukYaroslav** [comment]
Было пофикшено ряд ховер эффектов, вынесено блок копирайта из вне списка, также изменена структура, что позволило видить правильное расположение элементов в основных браузерах

**Comment by andrewmarushko** [comment]
# Не зачет

Нужно поправить ховер эффект на главной менюшке без отезда в право, а в меню боковое наоборот добавить!

![screenshot 2015-11-04 08 10 24](https://cloud.githubusercontent.com/assets/4026421/10930915/897cf66e-82cb-11e5-90e7-dfd383391c51.png)

этот элемент спозеционирован не корректно такой margin с права большой это признак плохого верстальщика!

А так все остальное уже не плохо получаеться поправь эти 3 бага и в принципе все з этой домашкой

**Comment by YurchukYaroslav** [comment]
Все замечания устранены

**Comment by andrewmarushko** [comment]
# DONE!
