### ISSUE TITLE
dz Rewiev lessons 5

### ISSUE THREAD

**Issue by andrewmarushko** [YurchukYaroslav/YurchukYaroslav.github.io#2]
# НЕ ЗАЧЕТ

эту кнопочку нужно делать одним линком одним тегом "а", картинку можно вставить либо бг для ссылки или же спаном спаном лучше т.к там есть бордер по правой стороне

<img width="162" alt="screenshot 2015-11-13 10 07 52" src="https://cloud.githubusercontent.com/assets/4026421/11141552/089c47d6-89ef-11e5-8bb0-af3f5b7c05ab.png">

**Comment by andrewmarushko** [comment]
- [x] нежно поправить этот момент через :before  :affter!

<img width="177" alt="screenshot 2015-11-14 15 32 09" src="https://cloud.githubusercontent.com/assets/4026421/11163786/13121816-8ae5-11e5-8491-dea5e102c579.png">

**Comment by YurchukYaroslav** [comment]
Баги устранены, face поместил на одну кнопку, before, after использованы для ou

**Comment by andrewmarushko** [comment]
# Done!

**Comment by andrewmarushko** [comment]
# НЕ ЗАЧЕТ
- [ ] - не соответсвует макету меню

<img width="780" alt="screen shot 2015-12-08 at 10 41 07 pm" src="https://cloud.githubusercontent.com/assets/4026421/11667873/f791793a-9dfc-11e5-9726-e3a1bad96842.png">

**Comment by YurchukYaroslav** [comment]
Поправил 5-е и 6-е задание
