### ISSUE TITLE
Dz review 6 ( Zazor )

### ISSUE THREAD

**Issue by andrewmarushko** [YurchukYaroslav/YurchukYaroslav.github.io#3]
# НЕ ЗАЧЕТ
- [x]  При клике не проподает нужно поправить.

<img width="268" alt="screen shot 2015-12-08 at 10 46 15 pm" src="https://cloud.githubusercontent.com/assets/4026421/11668161/40d7f06e-9dfe-11e5-9b83-af6e4ae948b9.png">
- [x]  текст вылазит за рамки

<img width="262" alt="screen shot 2015-12-08 at 10 52 10 pm" src="https://cloud.githubusercontent.com/assets/4026421/11668282/045e35a2-9dff-11e5-9e56-6bde12dd061f.png">

**Comment by YurchukYaroslav** [comment]
Данные баги исправлены
